//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoriyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blackurl
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public string Url { get; set; }
    }
}
