

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NoriyWeb.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class NoriyEntities : DbContext
{
    public NoriyEntities()
        : base("name=NoriyEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<Blackurl> Blackurls { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<CategoryLink> CategoryLinks { get; set; }

    public virtual DbSet<FacebookId> FacebookIds { get; set; }

    public virtual DbSet<Friendship> Friendships { get; set; }

    public virtual DbSet<Traffic> Traffic { get; set; }

    public virtual DbSet<UrlBlacklist> UrlBlacklists { get; set; }

    public virtual DbSet<Danger> Dangers { get; set; }

}

}

