//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoriyWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModelContainer : DbContext
    {
        public DbModelContainer()
            : base("name=DbModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Traffic> Traffic { get; set; }
        public virtual DbSet<UrlBlacklist> UrlBlacklists { get; set; }
        public virtual DbSet<Friendship> Friendships { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<FacebookId> FacebookIds { get; set; }
        public virtual DbSet<CategoryLink> CategoryLinks { get; set; }
        public virtual DbSet<Blackurl> Blackurls { get; set; }
    }
}
